name: CI/CD Test Build

on:
    push:
        branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Add VPS to known_hosts
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
                chmod 600 ~/.ssh/deploy_key
                ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        
            - name: Deploy frontend
              run: |
                rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
                    frontend/ \
                    ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/vps-ftp/ftp/files/portfolio/

            - name: Deploy backend
              run: |
                rsync -avz --exclude='.env' -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
                    backend/ \
                    ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/vps-ftp/ftp/files/portfolio_backend/

            
            - name: Post-deploy optimization
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd /home/vps-ftp/ftp/files/portfolio_backend
                    php artisan optimize